# Generated by Django 5.2.1 on 2025-06-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='critical_level',
            field=models.PositiveIntegerField(default=10, help_text='Minimum stok eşiği'),
        ),
    ]
