# Generated by Django 5.2.1 on 2025-06-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockmovement_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('adet', 'Adet'), ('kg', 'Kilogram'), ('koli', 'Koli'), ('palet', 'Palet'), ('lt', 'Litre')], default='adet', max_length=10, verbose_name='Birim'),
        ),
    ]
