# Generated by Django 5.2.1 on 2025-06-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('adet', 'Adet'), ('kilo', 'Kilo'), ('koli', 'Koli'), ('palet', 'Palet'), ('çuval', 'Çuval'), ('kasa', 'Kasa'), ('teneke', 'Teneke')], default='adet', max_length=10, verbose_name='Birim'),
        ),
    ]
