# Generated by Django 5.2.3 on 2025-06-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="critical_level",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Minimum stok eşiği",
                verbose_name="Minimum Stok Eşiği",
            ),
        ),
    ]
