# Generated by Django 5.2.3 on 2025-06-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0009_alter_product_critical_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="max_temperature",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Maksimum Sıcaklık (°C)"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="min_temperature",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Minimum Sıcaklık (°C)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="critical_level",
            field=models.PositiveIntegerField(
                default=10, verbose_name="Minimum Stok Eşiği"
            ),
        ),
    ]
