# Generated by Django 5.2.3 on 2025-06-15 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_product_max_temperature_product_min_temperature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="stock_obj",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="inventory.stock",
            ),
            preserve_default=False,
        ),
    ]
